# Generated by Django 4.0.5 on 2022-06-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rename_businesscategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category1',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category2',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('offline', 'Off-line'), ('online', 'Online'), ('both', 'Both')], default='offline', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category', 'subcategory')},
        ),
    ]
