# Generated by Django 4.0.5 on 2022-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_subcategory_options_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
