# Generated by Django 4.0.5 on 2022-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_average_rating_business_total_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
