# Generated by Django 4.0.5 on 2022-07-10 03:53

import businesses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_replayreview_is_active_review_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, choices=[('VA', 'Virginia'), ('MD', 'Mary Land'), ('DC', 'District of Columbia')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[businesses.models.zipcode_validator]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '형편없다'), (2, '별로다'), (3, '보통이다'), (4, '좋다'), (5, '아주좋다')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
