# Generated by Django 4.0.5 on 2022-07-10 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_replayreview_is_active_review_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '형편없다'), (2, '별로다'), (3, '보통이다'), (4, '좋다'), (5, '아주좋다')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
