# Generated by Django 4.0.5 on 2022-07-10 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_alter_business_address_alter_business_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='business',
            name='total_rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
